//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BUSES
    {
        public BUSES()
        {
            this.BUSES_RUTAS = new HashSet<BUSES_RUTAS>();
        }
    
        public string IdBus { get; set; }
        public string PlacaBus { get; set; }
    
        public virtual ICollection<BUSES_RUTAS> BUSES_RUTAS { get; set; }
    }
}
