//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BUSES_RUTAS
    {
        public BUSES_RUTAS()
        {
            this.DETALLE_FACTURA = new HashSet<DETALLE_FACTURA>();
            this.PUESTOS = new HashSet<PUESTOS>();
        }
    
        public int IdBusRuta { get; set; }
        public string idBus { get; set; }
        public int IdRuta { get; set; }
        public System.DateTime FechaRuta { get; set; }
    
        public virtual BUSES BUSES { get; set; }
        public virtual RUTAS RUTAS { get; set; }
        public virtual ICollection<DETALLE_FACTURA> DETALLE_FACTURA { get; set; }
        public virtual ICollection<PUESTOS> PUESTOS { get; set; }
    }
}
