//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CIUDADES
    {
        public CIUDADES()
        {
            this.RUTAS = new HashSet<RUTAS>();
            this.RUTAS1 = new HashSet<RUTAS>();
        }
    
        public int IdCiudad { get; set; }
        public string NombreCiudad { get; set; }
    
        public virtual ICollection<RUTAS> RUTAS { get; set; }
        public virtual ICollection<RUTAS> RUTAS1 { get; set; }
    }
}
