//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_FACTURA
    {
        public int IdDetalleFactura { get; set; }
        public decimal Valor { get; set; }
        public int IdBusesRuta { get; set; }
        public int IdFactura { get; set; }
    
        public virtual BUSES_RUTAS BUSES_RUTAS { get; set; }
        public virtual FACTURAS FACTURAS { get; set; }
    }
}
