//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACTURAS
    {
        public int IdFactura { get; set; }
        public System.DateTime FechaFactura { get; set; }
        public string IdCliente { get; set; }
    
        public virtual CLIENTES CLIENTES { get; set; }
        public virtual DETALLE_FACTURA DETALLE_FACTURA { get; set; }
    }
}
