//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RUTAS
    {
        public RUTAS()
        {
            this.BUSES_RUTAS = new HashSet<BUSES_RUTAS>();
            this.HORARIOS = new HashSet<HORARIOS>();
        }
    
        public int IdRuta { get; set; }
        public int CiudadOrigen { get; set; }
        public int CiudadDestino { get; set; }
        public decimal Valor { get; set; }
    
        public virtual ICollection<BUSES_RUTAS> BUSES_RUTAS { get; set; }
        public virtual CIUDADES CIUDADES { get; set; }
        public virtual CIUDADES CIUDADES1 { get; set; }
        public virtual ICollection<HORARIOS> HORARIOS { get; set; }
    }
}
